### ISSUE TITLE
Small corrections, and a couple of questions

### ISSUE THREAD

**Issue by bogd** [hallard/WeMos-Matrix-Shield-DMA#1]
First of all, thank you for the great work you did on this - it was the only open-source PCB that I could find for the I2S library! Your work is truly appreciated!!

A few (very small) things you may want to fix in the next version:
- the silkscreen on the back still shows a G0 (on the front it has G1 for the same pin)
- on the silkscreen, you have links to your and mrfaptastic's github pages - unfortunately, the links partly overlap with the cutouts in the board, so they can be difficult to read

Also, a couple of questions for you:
- what type of screw terminal are you using? Because the ones that I could source (such as [this one](https://www.aliexpress.com/item/4000600315390.html?spm=a2g0o.productlist.0.0.45e76aa7FCHbvk&algo_pvid=153f9552-a0c5-4ca6-8649-fe178306d63f&algo_expid=153f9552-a0c5-4ca6-8649-fe178306d63f-10&btsid=2100bb5116182169423125578e782c&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_) ) all have the pins offset from the center - while the footprint on your board has the pins fully centered
[ Edit - found them! Thanks to the link you posted, I managed to find them [here](https://www.aliexpress.com/item/32359125431.html?spm=a2g0o.productlist.0.0.7f8c3a76zhlZyL&algo_pvid=dd58accf-303d-407a-a023-c43f2c3f9a1e&algo_expid=dd58accf-303d-407a-a023-c43f2c3f9a1e-1&btsid=2100bdd016182188494048551ef191&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_). They just seem to be a... rare breed, compared to the asymmetrical ones :) )
- what type of connector should I use for the 5V/GND connector on the side of the board? I originally assumed it would be something like [this](https://www.aliexpress.com/item/1005002157208121.html?spm=a2g0o.productlist.0.0.213164806HM5eL&algo_pvid=f07ca85d-afaa-41b5-8cb2-cafa7b5178d0&algo_expid=f07ca85d-afaa-41b5-8cb2-cafa7b5178d0-1&btsid=2100bdd816182171400728944ecc8c&ws_ab_test=searchweb0_0,searchweb201602_,searchweb201603_), but it seems to have different pin spacing
[ Edit - found this one as well, by looking at the schematic. It is a KK-156-4 connector. I would guess [this one](https://eu.mouser.com/ProductDetail/Molex/76650-0102?qs=5NHWMpvrJ2C2NvuJzvI7ew%3D%3D)? ]
- did I understand the T9/IO32 pad correctly? Is it designed to work as a touch sensor? If so, can you tell us how  to read it from code? 
[ Edit - found this one as well :) . The ESP32 has dedicated touch pins - T9 being "Touch 9". A nice tutorial on using them is [here](https://randomnerdtutorials.com/esp32-touch-pins-arduino-ide/) 

So my questions have been answered - however, I will leave them here, in case you may want to add some additional info to the documentation for the board (such as the touchpin tutorial linked above)
].

Once again, a big _thank you_ for your work on this!!

**Comment by hallard** [comment]
@bogd Nice you found your answers, sure sometimes link on aliexpress change and product also so it's complicated to keep them up to date.

Thank you for sharing your answer and links.

Have fun

**Comment by bogd** [comment]
@hallard - thank you once again. I truly appreciate all the work you put into this, and the fact that you open sourced the project. In fact, your work gave me the courage to start building my own version of the matrix shield (and, of course, I open sourced that as well - share and share alike :) ). 

I will close this issue now, since all my questions have been answered. Once again, a big thank you!!
